server:
  port: 0
  shutdown: graceful
spring: 
 cloud:
    config:
      # Allow the microservices to override the remote properties with their own System properties or config file
      allow-override: true
      # Override configuration with any local property source
      override-none: true 
  jpa:
     hibernate:
       ddl-auto: update
     database: mysql
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://stockmarketdatabase.mysql.database.azure.com:3306/stockmarketdb?useSSL=true
     username: stockmarketuser1
     password: Test@1234 
            
logging.level.org.springframework: INFO

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true      
